trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Build
    jobs:
      - job : Job1
        steps:
         - bash : echo Build Job1
         - bash: echo $(PipelineLevelVariable)
         - bash: echo $(Build.BuildNumber)
         - bash: echo $(Build.BuildId)
         - bash: echo $(Build.SourceBranchName)
         - bash: echo $(Build.SourcesDirectory)
         - bash: echo $(System.DefaultWorkingDirectory)
         - bash: ls -R $(System.DefaultWorkingDirectory)
         - bash: echo $(Build.ArtifactStagingDirectory) 
         - bash: java -version
         - bash: node --version
         - bash: python --version 
         - bash: mvn -version
         - bash: ls -R $(Build.ArtifactStagingDirectory)
         - task: CopyFiles@2
           inputs:
            SourceFolder: '$(System.DefaultWorkingDirectory)'
            Contents: |
              **/*.yaml
              **/*.tf
            TargetFolder: '$(Build.ArtifactStagingDirectory)'
         - bash: ls -R $(Build.ArtifactStagingDirectory)
      # - job : Job2
      #   steps:
      #    - bash : echo Build Job2
  # - stage: DEV
  #   variables:
  #     environment: DEV 
  #   dependsOn: Build
  #   jobs:
  #     - job : DEVJob1
  #       steps:
  #        - bash : echo $(environment)Job1
  # - stage: QA
  #   variables:
  #     environment: QA 
  #   dependsOn: Build
  #   jobs:
  #     - job : QAJob1
  #       steps:
  #        - bash : echo $(environment)Job1
  # - stage: PROD
  #   dependsOn:
  #   - Dev
  #   - QA
  #   jobs:
  #     - job : PRODJob1
  #       steps:
  #        - bash : echo PRODJob1
